discord:
  enabled: true
  token: "NzcyNTI4MTg5Njc1Mjc0Mjcw.G1laQA.UZv7v6qSvrjfcSoq6z6_9jfvva9ZyECCHy9Z8g"
  guild-id: "1404292846340542554"

databases:
  ranked:
    host: "db-mfl-01.apollopanel.com"
    port: "3306"
    database: "s211319_ranked_db"
    username: "u211319_Ad6KwoO4z0"
    password: "ZuWzGA^@!eeJaftDXqEBlJmy"

  match_logs:
    host: "db-mfl-01.apollopanel.com"
    port: "3306"
    database: "s211319_match_logs_db"
    username: "u211319_rLXIzfmmdO"
    password: "!=zz@6yiVm^iruU66ix6e3cL"

forfeit:
  # primeros 3 minutos: /ff bloqueado
  lock-seconds: 180

  # si hay AFK/DC: deben pasar X segundos desde que se detectó para permitir /ff
  issue-wait-seconds: 60

  # a los X segundos sin moverse ya cuenta como AFK (y puede kickearse)
  afk-detect-seconds: 20

  afk-kick:
    enabled: true
    message: "&cHas sido expulsado por AFK en partida. &7Si fue un error, vuelve a entrar."

abandonment:
  # tiempo que permites para que alguien vuelva tras desconexión antes de marcar abandono
  reconnect-grace-seconds: 120
